
language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls
  - travis_retry composer require phpstan/phpstan-shim
  - travis_retry composer install --no-interaction --prefer-source
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml
  - php vendor/bin/phpstan analyse --level=7 --configuration=phpstan.neon src

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - bash <(curl -s https://codecov.io/bash)
